name: Deploy to Coolify

on:
  push:
    branches:
      - main   # or master, whichever you use

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: curl -X POST "${{ secrets.COOLIFY_DEPLOY_URL }}"
